forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
	path('', views.posts_list, name='index'),
	path('<int:pk>', views.post_detail, name='post'),
	path('<int:pk>/edit/', views.post_edit, name='post_edit'),
	path('<int:pk>/answer/', views.add_answer, name="add_answer"),
	path('delete/<int:an>', views.delete_answer, name="delete_answer"),
	path('post', views.post_new, name='new_post'),
]

p_w_i/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('<int:pk>/', views.user_detail, name='index'),
    path("edit/<int:pk>/", views.edit_user_profile, name="user_info"),
    path('rejestruj/', views.SignUp.as_view(), name='rejestruj'),
    path('loguj/', views.loguj_user, name='loguj'),
    path('wyloguj/', views.wyloguj_user, name='wyloguj'),
]

forum/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(blank=True, null=True)
    views = models.IntegerField(default=0)

    def __str__(self):  # Definiujemy funkcje, która zwraca tytuł wpisu
        return self.title


class Answer(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='answers')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = "answers"

forum/forms.py
from django import forms
from .models import Post, Answer


class PostForm(forms.ModelForm):
    title = forms.CharField(
        label="Tytuł",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    description = forms.CharField(
        label="Treść",
        max_length=500,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Post
        fields = ('title', 'description',)


class AnswerForm(forms.ModelForm):
    text = forms.CharField(
        label="Komentarz",
        max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Answer
        fields = ('text',)

forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Answer
from django.utils import timezone
from .forms import PostForm, AnswerForm
from django.core.paginator import Paginator


def posts_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'forum/index.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'forum/post.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.author.id = request.user.id
            post.published_date = timezone.now()
            post.save()
            return redirect('forum:post', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'forum/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('forum:post', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'forum/post_edit.html', {'form': form})


def add_answer(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.author.id = request.user.id
            answer.post = post
            answer.save()
            return redirect('forum:post', pk=post.pk)
    else:
        form = AnswerForm()
    return render(request, 'forum/comments.html', {'form': form})


def delete_answer(request, an,):
    answer = get_object_or_404(Answer, pk=an)
    answer.delete()
    return redirect('forum:index')

forum/templates/forum/comments.html
{% extends 'szablon.html' %}
{% block tresc %}

    {% if user.is_authenticated %}
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button onclick="{% url 'forum:index' %}" type="submit" class="save btn btn-info">Dodaj</button>
        </form>
    {% else %}
        <a href="{% url 'users:loguj' %}" class="btn btn-info" role="button">Zaloguj</a>
    {% endif %}

{% endblock tresc %}

forum/templates/forum/index.html
{% extends 'szablon.html' %}
{% block tresc %}

    <div class="container d-inline-block w-80">
        {% if user.is_authenticated %}
            <p><a href="{% url 'forum:new_post' %}" class="btn btn-info" role="button">Nowy post</a></p>
        {% else %}
            <p><a href="{% url 'users:loguj' %}" class="btn btn-info" role="button">Zaloguj</a></p>
        {% endif %}
    </div>

    <div class="container w-80">
    {% for post in posts %}
<!--        <h1><a href="{% url 'forum:post' pk=post.pk %}">{{ post.title }}</a></h1>-->
<!--        <h6>-->
<!--            Autor: <a href="{% url 'users:index' pk=post.author.id %}">{{ post.author }}</a> | {{ post.published_date }}-->
<!--        </h6>-->
<!--        <p>{{ post.description|linebreaksbr|truncatechars:30 }}</p>-->

        <div class="card w-100 mt-3" style="float: left;">
            <div class="card-header">
                <h4 class="card-title"><a href="{% url 'forum:post' pk=post.pk %}">{{ post.title }}</a></h4>
                <h6 class="card-subtitle">{{ post.published_date }}</h6>
            </div>
            <div class="card-body">
                <p class="card-text">{{ post.description|linebreaksbr|truncatechars:30 }}</p>
                Autor: <a href="{% url 'users:index' pk=post.author.id %}">{{ post.author }}</a>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="container d-inline-block w-80 justify-content-center">
      {% if posts.has_other_pages %}
        <ul class="pagination mt-3">
          {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo; Poprzednia</a></li>
          {% else %}
            <li class="disabled page-item"><span class="page-link">&laquo; Poprzednia</span></li>
          {% endif %}
          {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
              <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(obecna)</span></span></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if posts.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Następna &raquo;</a></li>
          {% else %}
            <li class="disabled page-item"><span class="page-link">Następna &raquo;</span></li>
          {% endif %}
        </ul>
      {% endif %}
    </div>

{% endblock tresc %}

forum/templates/forum/post.html
{% extends 'szablon.html' %}
{% block naglowek %}
<!--        <a href="{% url 'forum:post' pk=post.pk %}">{{ post.title }}</a>-->
    <div class="container border rounded mt-3">
        <h1>{{ post.title }}
        {% if user.is_authenticated and user == post.author %}
            <a class="btn btn-default" href="{% url 'forum:post_edit' pk=post.pk %}">Edytuj</a>
        {% endif %}
        </h1>
        <h6>Autor: <b><a href="{% url 'users:index' pk=post.author.id %}">{{ post.author }}</a></b><br> Data publikacji: {{ post.published_date }}</h6>
        <div class="dropdown-divider"></div>
        <h4>{{ post.description|linebreaksbr }}</h4>
    </div>
{% endblock naglowek %}
{% block tresc %}

        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'forum:add_answer' pk=post.pk %}">Dodaj komentarz</a>
        {% else %}
            <div class="alert alert-info">
                <p>Aby dodac kometarz musisz byc zalogowany</p>
                <a href="{% url 'users:loguj' %}" class="btn btn-info" role="button">Zaloguj</a>
            </div>
        {% endif %}
        {% for answer in post.answers.all %}
<!--            <table class="table">-->
<!--            <tr class="info">-->
<!--                <td><a href="{% url 'users:index' pk=answer.author.id %}">{{ answer.author }}</a></td>-->
<!--            <td><strong>{{ answer.published_date }}</strong></td>-->
<!--            {% if user == answer.author %}-->
<!--                <td><a href="{% url 'forum:delete_answer' an=answer.id %}">Usun</a></td>-->
<!--            {% endif %}-->
<!--            </tr>-->

<!--            <tr class="info">-->
<!--                <td colspan="2">{{ answer.text|linebreaks|truncatechars:30 }}</td>-->
<!--            </tr></table>-->

            <div class="card mt-3">
                <div class="card-header">
                    <h5 class="card-title">
                        <a href="{% url 'users:index' pk=answer.author.id %}">{{ answer.author }}</a>
                        {% if user == answer.author %}
                        <a href="{% url 'forum:delete_answer' an=answer.id %}">[Usun]</a>
                        {% endif %}
                    </h5>
                    <h6 class="card-subtitle">
                        {{ answer.published_date }}
                    </h6>
                </div>
                <div class="card-body">
                    <div class="card-text">
                        {{ answer.text|truncatechars:30 }}
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Brak komentarzy :(</p>
        {% endfor %}

{% endblock tresc %}

forum/templates/forum/post_edit.html
{% extends 'szablon.html' %}
{% block tresc %}

    {% if user.is_authenticated %}
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-info" role="button">Zatwierdz zmiany</button>
        </form>
    {% else %}
        <a href="{% url 'users:loguj' %}" class="btn btn-info" role="button">Zaloguj</a>
    {% endif %}

{% endblock tresc %}