forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
	path('', views.posts_list, name='index'),
	path('<int:pk>', views.post_detail, name='post'),
	path('<int:pk>/edit/', views.post_edit, name='post_edit'),
	path('<int:pk>/answer/', views.add_answer, name="add_answer"),
	path('delete/<int:an>', views.delete_answer, name="delete_answer"),
	path('post', views.post_new, name='new_post'),
]

p_w_i/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('<int:pk>/', views.user_detail, name='index'),
    path("edit/<int:pk>/", views.edit_user_profile, name="user_info"),
    path('rejestruj/', views.SignUp.as_view(), name='rejestruj'),
    path('loguj/', views.loguj_user, name='loguj'),
    path('wyloguj/', views.wyloguj_user, name='wyloguj'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100, default='', blank=True)
    bio = models.TextField(default='', blank=True)

    def create_profile(sender, **kwargs):  # Funckja, ktora tworzy profile użytkownika
        user = kwargs["instance"]
        if kwargs["created"]:
            user_profile = UserProfile(user=user)
            user_profile.save()

    post_save.connect(create_profile, sender=User)

    def __str__(self):  # Definiujemy funkcje, która zwraca tytuł wpisu
        return self.user.username

users/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    login = forms.CharField(
        label="Twój login",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    haslo = forms.CharField(
        label="Twoje hasło",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password'})
    )


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(
        label="Imię",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    last_name = forms.CharField(
        label="Nazwisko",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    email = forms.CharField(
        label="email",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email"
        ]


class EditUserProfileForm(forms.ModelForm):
    city = forms.CharField(
        label="Miasto",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    bio = forms.CharField(
        label="Bio",
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = UserProfile
        fields = [
            "city",
            "bio"
        ]

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from users.forms import UserLoginForm, EditUserForm, EditUserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def loguj_user(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            nazwa = form.cleaned_data['login']
            haslo = form.cleaned_data['haslo']
            user = authenticate(request, username=nazwa, password=haslo)
            if user is not None:
                login(request, user)
                messages.success(request, "Zostałeś zalogowany!")
                return redirect(reverse('forum:index'))
            else:
                messages.error(request, "Błędny login lub hasło!")
    else:
        form = UserLoginForm()

    kontekst = {'form': form}
    return render(request, 'users/loguj_user.html', kontekst)


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('forum:index')
    template_name = 'users/loguj_user.html'


def wyloguj_user(request):
    logout(request)
    messages.info(request, "Zostałeś wylogowany!")
    return redirect(reverse('forum:index'))


def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    userprofile = user.userprofile
    return render(request, 'users/index.html', {'userprofile': userprofile})


def edit_user_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    user_profile = user.userprofile

    user_form = EditUserForm(request.POST or None, instance=user)
    profile_form = EditUserProfileForm(request.POST or None, instance=user_profile)

    if request.method == "POST" and user_form.is_valid() and profile_form.is_valid():
        user_form.save()
        profile_form.save()
        return redirect(f"/users/{pk}")

    return render(request, "users/user_info.html", {
        "user_form": user_form,
        "profile_form": profile_form
    })

users/templates/users/index.html
{% extends 'szablon.html' %}

{% block tresc %}
    {% load crispy_forms_tags %}

    {% if user.is_authenticated %}
        {% csrf_token %}
        <div class="card" style="width:400px">
            <div class="card-header"><h4> Profil {{ userprofile.user.username }}:</h4></div>
            <img class="card-img-top rounded-circle mx-auto d-block mt-2" src="https://thispersondoesnotexist.com/image" alt="Card image" style="width:300px">
            <div class="dropdown-divider"></div>
            <div class="card-body">
                <p>Imie: <b>{{ userprofile.user.first_name }}&nbsp</b></p>
                <p>Nazwisko: <b>{{ userprofile.user.last_name }}&nbsp</b></p>
                <p>Email: <b>{{ userprofile.user.email }}&nbsp</b></p>
                <p>Miasto: <b>{{ userprofile.city }}&nbsp</b></p>
                <p>Bio: <b>{{ userprofile.bio }}&nbsp</b></p>
            {% if user.username == userprofile.user.username %}
                <p><a href="{% url 'users:user_info' pk=user.id %}" class="btn btn-info" role="button">Edytuj dane<span class="glyphicon glyphicon-pencil"></span></a></p>
            {% endif %}
            </div>
        </div>
    {% else %}
        <form action="." method="POST">
            <div class="alert alert-info">
                <p> Aby zobaczyc profil musisz byc zalogowany</p>
                <a href="{% url 'users:loguj' %}" class="btn btn-info" role="button">Zaloguj</a></p>
            </div>
        </form>
    {% endif %}

{% endblock tresc %}

users/templates/users/loguj_user.html
{% extends 'szablon.html' %}
{% block naglowek %}Logowanie{% endblock naglowek %}
{% block tresc %}

    {% if user.is_authenticated %} {% csrf_token %}
        <p>Jesteś już zalogowany jako {{ user.username }}.</p>
    {% else %}
        <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button onclick="{% url 'forum:index' %}" type="submit" class="btn btn-info">Zaloguj</button>
        </form>
    {% endif %}

{% endblock tresc %}

users/templates/users/user_info.html
{% extends 'szablon.html' %}
{% block tresc %}

    {% if user.is_authenticated %}
        <h2>Edytuj dane: </h2>
        <form method="POST">
            {% csrf_token %}
                {{ user_form }}
                {{ profile_form }}
            <input type="submit" onclick="{% url 'users:index' pk=user.id%}" value="Zapisz" class="btn btn-info">
        </form>
    {% else %}
        <form action="." method="POST">
        <a href="{% url 'users:loguj' %}" class="btn btn-info" role="button">Zaloguj</a>
        </form>
    {% endif %}
{% endblock tresc %}