forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
	path('', views.posts_list, name='index'),
	path('<int:pk>', views.post_detail, name='post'),
	path('<int:pk>/edit/', views.post_edit, name='post_edit'),
	path('<int:pk>/answer/', views.add_answer, name="add_answer"),
	path('delete/<int:an>', views.delete_answer, name="delete_answer"),
	path('post', views.post_new, name='new_post'),
]

p_w_i/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('<int:pk>/', views.user_detail, name='index'),
    path("edit/<int:pk>/", views.edit_user_profile, name="user_info"),
    path('rejestruj/', views.SignUp.as_view(), name='rejestruj'),
    path('loguj/', views.loguj_user, name='loguj'),
    path('wyloguj/', views.wyloguj_user, name='wyloguj'),
]

templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tytul %}Forum internetowe Programowania w Internecie{% endblock tytul %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark">
        <a class="navbar-brand text-white" href="{% url 'forum:index' %}">Forum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown" role="button">Konto</a>
                    <div class="dropdown-menu">
                        {% if not user.is_authenticated %}
                            <a href="{% url 'users:rejestruj' %}" class="dropdown-item">Załóż konto</a>
                            <a href="{% url 'users:loguj' %}" class="dropdown-item">Zaloguj</a>
                        {% else %}
                            <a href="{% url 'users:index'  pk=user.id %}" class="dropdown-item">Profil</a>
                            <a href="{% url 'users:wyloguj' %}" class="dropdown-item">Wyloguj</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col">

<h1>{% block naglowek %}{% endblock naglowek %}</h1>

{% block komunikaty %}
{% if messages %}
    <ul>
    {% for komunikat in messages %}
        <li>{{ komunikat }}</li>
    {% endfor %}
    </ul>
{% endif %}
{% endblock komunikaty %}

{% block tresc %}
{% endblock tresc %}

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>